name: Build and Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build core modules
      run: ./gradlew :annotations:build :transpiler:build
      
    - name: Run tests
      run: ./gradlew :annotations:test :transpiler:test
      
    - name: Verify transpiler functionality
      run: java -jar transpiler/build/libs/transpiler-*.jar --help || true
      
    - name: Build transpiler shadow JAR
      run: ./gradlew :transpiler:shadowJar
      
    - name: Upload transpiler JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: transpiler-jar
        path: transpiler/build/libs/transpiler-*.jar
        retention-days: 30